- name: Deploy Storybook to GitHub Pages
  # You may pin to the exact commit or the version.
  # uses: bitovi/github-actions-storybook-to-github-pages@c7d2a479f2ec3d87d1131357f328e0e40c60da20
  uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
  with:
    # Specifies if this action should checkout the code
    checkout: # optional, default is true
    # Specifies the path of the static assets after building
    path: # optional, default is dist/storybook
    # Specifies the command to run after npm ci for the build
    build_command: # optional, default is npm run build-storybook
